// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bot_entities.Repositories;

#nullable disable

namespace bot_entities.Migrations
{
    [DbContext(typeof(BotTelegramContext))]
    partial class BotTelegramContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bot_entities.Entities.UserEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("UserTelegramID")
                        .HasColumnType("text")
                        .HasColumnName("user_telegram_id");

                    b.Property<int>("Enum")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("UserId", "UserTelegramID");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
